FROM mcr.microsoft.com/devcontainers/base:jammy

# RUN git clone https://github.com/fema-ffrd/rasqc.git
# RUN cd rasqc/ && git checkout feature/stac-checker

# RUN pip install build && python -m build
# RUN pip install dist/rasqc-0.0.1rc1-py3-none-any.whl


# RUN cd .. && python -m build
# RUN pip install dist/hecstac-0.1.0rc3-py3-none-any.whl

# RUN cd ..

