name: Docker Build

on:
  workflow_call:
    inputs:
      push_to_registry:
        type: boolean
        default: false
        required: false
      version:
        type: string
        required: true
      branch:
        type: string
        required: true
      platforms:
        type: string
        default: 'linux/amd64'
        required: false

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tags.outputs.TAGS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker tags based on branch
        id: set_tags
        run: |
          if [[ "${{ inputs.branch }}" == "main" ]]; then
            echo "TAGS=ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ inputs.version }}" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.branch }}" == "dev" ]]; then
            echo "TAGS=ghcr.io/${{ github.repository }}:${{ inputs.version }}-dev" >> $GITHUB_OUTPUT
          else
            echo "TAGS=ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: inputs.push_to_registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push_to_registry }}
          tags: ${{ steps.set_tags.outputs.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-scout:
    needs: build-docker
    if: always()
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/docker-scout.yaml
    with:
      image_tag: ${{ needs.build-docker.outputs.image_tag || 'ghcr.io/fema-ffrd/hecstac:latest' }}
    secrets: inherit