name: Docker Scout Security Scan

permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        required: true
        description: 'Docker image tag to scan'
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM UTC

jobs:
  docker-scout:
    name: Docker Scout Scan
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets availability
        run: |
          echo "DOCKER_USER exists: ${{ secrets.DOCKER_USER != '' }}"
          echo "DOCKER_PAT exists: ${{ secrets.DOCKER_PAT != '' }}"
          echo "DOCKER_USER length: ${{ length(secrets.DOCKER_USER) }}"
          echo "DOCKER_PAT length: ${{ length(secrets.DOCKER_PAT) }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Scout CVE scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ inputs.image_tag || 'ghcr.io/fema-ffrd/hecstac:latest' }}
          only-severities: critical,high
          summary: true