name: Main Branch Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'hecstac/**'
      - 'tests/**'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/**'
      - 'pyproject.toml'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  python-build:
    name: Python Build and Test
    uses: ./.github/workflows/python-build.yaml
    with:
      run_tests: false
      
  get-version:
    name: Extract Package Version
    uses: ./.github/workflows/get-version.yaml

  docker-build-push:
    name: Build and Push Docker Image
    needs: [python-build, get-version]
    uses: ./.github/workflows/docker-build.yaml
    with:
      push_to_registry: true
      version: ${{ needs.get-version.outputs.version }}
      branch: 'main'
      platforms: 'linux/amd64'

  pypi-publish:
    name: Publish to PyPI
    needs: [python-build, get-version]
    uses: ./.github/workflows/pypi-publish.yaml
    with:
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  github-release:
    name: Create GitHub Release
    needs: [python-build, pypi-publish, get-version]
    uses: ./.github/workflows/github-release.yaml
    with:
      version: ${{ needs.get-version.outputs.version }}