name: PR Checks

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'hecstac/**'
      - 'tests/**'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/**'
      - 'pyproject.toml'

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  python-build:
    name: Python Build and Test
    uses: ./.github/workflows/python-build.yaml
    with:
      run_tests: false

  sonarqube:
    name: SonarQube Analysis
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: ./.github/workflows/sonarqube.yaml

  get-version:
    name: Extract Package Version
    uses: ./.github/workflows/get-version.yaml

  docker-build-test:
    name: Test Docker Build
    needs: get-version
    uses: ./.github/workflows/docker-build.yaml
    with:
      push_to_registry: true
      version: ${{ needs.get-version.outputs.version }}
      branch: ${{ github.base_ref }}
      platforms: 'linux/amd64'
    secrets: inherit

  docker-scout:
    needs: docker-build-test
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/docker-scout.yaml
    with:
      image_tag: ${{ needs.docker-build-test.outputs.image_tag }}
    secrets: inherit
