name: PyPI Publish

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: "Version to publish to PyPI"
    secrets:
      PYPI_TOKEN:
        required: true
        description: "PyPI API token for authentication"

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install publishing dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          
      - name: Build wheel and source distribution
        run: python -m build
        
      - name: List dist directory contents
        run: dir dist
        
      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python -m twine upload dist/*